### ISSUE TITLE
Is there a way to enforce a LLM to generate a JSON without excessive whitespaces?

### ISSUE THREAD

**Issue by LorrinWWW** [noamgat/lm-format-enforcer#52] opened 2024-01-06 08:56 UTC
Can we enforce a LLM to generate a more structured JSON format? 
~~Currently, it might produce excessive whitespaces and occasionally ends with an EOS token without even closing the bracket.~~ (Actually, I found this is actually due to an issue in my schema.. But I am still curious about how to further constrain the model)
Can we limit the flexibility of the LLM to ensure it only generates valid JSON objects, without excessive whitespaces?
Thank you so much!

**Comment by noamgat** [comment] 2024-01-07 11:46
Its currently not exposed via an API, but if you fork your own version, and change `MAX_CONSECUTIVE_WHITESPACES = 12` to something else (0 probably) in `consts.py`, you should get the behavior you are looking for. I'm leaving this issue open and flagging it as an enhancement, to see if others are interested in it.

**Comment by JoshC8C7** [comment] 2024-01-08 15:05
+1 for the conf.py params being exposed ! can make a PR if I get a second.

**Comment by QuangBK** [comment] 2024-01-11 03:12
+1

**Comment by kongjiellx** [comment] 2024-01-11 09:39
+1

**Comment by fergusbarratt** [comment] 2024-02-05 14:54
+1

**Comment by davidsyoung** [comment] 2024-02-14 17:19
+1

**Comment by juanhuguet** [comment] 2024-04-08 11:07
+1

**Comment by noamgat** [comment] 2024-05-04 14:53
Released in v0.10.1. Can you check if you can now solve the problem via [Configuration Options](https://github.com/noamgat/lm-format-enforcer?tab=readme-ov-file#configuration-options)?

**Comment by noamgat** [comment] 2024-05-04 17:01
Should be supported now, please reopen if the issue is not solved.

**Closed by noamgat** 2024-05-04 17:01 UTC
Labels: enhancement
