### ISSUE TITLE
Array type incorectly restricts tokens

### ISSUE THREAD

**Issue by DrChristophFH** [noamgat/lm-format-enforcer#112] opened 2024-06-07 09:59 UTC
It seems as if the model is still allowed to produce "," tokens at the beginning of array types like so:

schema
```json
"instructions": {
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "if": {
        "type": "string"
      },
      "query": {
        "type": "string"
      }
    }
  }
}
```

generated
```json
"instructions": [
,{
"query": "..."
}]
```

which is not legal json.

**Comment by noamgat** [comment] 2024-06-17 18:17
Can you make sure you are using the latest version of the lib? Which integration is this through?

**Comment by noamgat** [comment] 2024-07-13 05:32
Closing the task due to the problem not reproducing on latest.

Code used to reproduce:
```
def test_bug_report_leading_comma():
    schema = {
        "properties": {
            "instructions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                    "if": {
                        "type": "string"
                    },
                    "query": {
                        "type": "string"
                    }
                    }
                }
            }
        },
        "type": "object"
    }
    completion = """{"instructions": [
    ,{
    "query": "..."
    }]}"""
    _test_json_schema_parsing_with_string(completion, schema, False)
```

**Closed by noamgat** 2024-07-13 05:32 UTC
